name: CDK destroy
on: workflow_dispatch

jobs:
  deploy:
    name: Destroy
    runs-on: ubuntu-latest
    env: 
      CDK_DEPLOY_REGION: eu-central-1
      CDK_DEPLOY_STACK_NAME: "${{ github.ref == 'refs/heads/main' && 'Prod' || 'Dev' }}"
      CDK_DEPLOY_ACCOUNT: "${{ github.ref == 'refs/heads/main' && '915661505220' || '601912882130' }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: 'maven'
      
      - name: install aws cdk
        run: "sudo npm install -g aws-cdk"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: CDK destroy
        run: cdk destroy --require-approval=never
