name: CDK PR
on: pull_request

jobs:
  deploy:
    name: Diff
    runs-on: ubuntu-latest
    env: 
      CDK_DEPLOY_REGION: eu-central-1
      CDK_DEPLOY_STACK_NAME: Prod
      CDK_DEPLOY_ACCOUNT: 915661505220
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: 'maven'

      - name: install aws cdk
        run: "sudo npm install -g aws-cdk"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK diff
        run: cdk diff --require-approval=never
